name: ITV Availability Checker

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  check-availability:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install playwright @playwright/test
        npx playwright install chromium
        
    - name: Install additional dependencies
      run: npm install
      
    - name: Run ITV availability checker
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: node playwright-checker.js
      
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: availability-results
        path: data.json
        retention-days: 7
