name: Run Availability Script

permissions:
  contents: write

on:
  schedule:
  - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  run-script:
    name: Run Availability Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node availability.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adds new properties (auto)
